title: Nic's diary
name: Niccolò Olivieri Achille
permalink: :year/:month/:day/:title
baseurl: /diary

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2013
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : n.olivieriachille@gmail.com
  github : Zweer
  twitter : dotzweer
  instagram: olivieriachille

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   About: "/about"
   Why: "/why"

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-feed