title: Nic's diary
name: Niccolò Olivieri Achille
permalink: :year/:month/:day/:title
baseurl: /diary

# Your blog's start year
start: 2013

# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : n.olivieriachille@gmail.com
  github : Zweer
  twitter : dotzweer
  instagram: olivieriachille

# Links in the navigation, you can modify both link name and link url
nav:
   About: "/about"
   Why: "/why"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

# Performance optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]
  blanklines: false
  profile: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
